### ISSUE TITLE
Issues in MakeFile: link flag should be at the end

### ISSUE THREAD

**Issue by ynandwan** [bartp5/gss#1]
In the Makefile, you need to give link flags in the end. It should look like `$(CC) $(CFLAGS) -o gss $(OBJ) $(LFLAGS)`. Otherwise, we get the linking error pasted at the end of this msg. Have a look at this post which helped me figure it out: https://stackoverflow.com/questions/11336477/gcc-will-not-properly-include-math-h

While compiling, I got the following error with the existing make file:

```sudoku_generator.c:(.text+0x5bd): undefined reference to `round'
sudoku_generator.o: In function `Rotate180':
sudoku_generator.c:(.text+0x6b5): undefined reference to `round'
sudoku_generator.o: In function `Rotate90':
sudoku_generator.c:(.text+0x8f4): undefined reference to `round'
sudoku_generator.o:sudoku_generator.c:(.text+0xd7f): more undefined references to `round' follow
collect2: error: ld returned 1 exit status
Makefile:46: recipe for target 'gss' failed
make: *** [gss] Error 1```

**Comment by bartp5** [comment]
you are quite right, I fixed it. Thanks for the feedback.
